### ISSUE TITLE
Where is the credit?

### ISSUE THREAD

**Issue by nurhazbiy** [TutorialsAndroid/AppXUpdater#2]
i think i saw the original of this module, but i can't see any credit in here, is it even safe to use it?

**Comment by TutorialsAndroid** [comment]
> i think i saw the original of this module, but i can't see any credit in here, is it even safe to use it?

This library was made and copied from a GitHub library. we actually made this because we want to use this library for personal use. because the original library was very old and no latest commits where their. And the most important thing the library that we copied from the GitHub we forgot the name of that library so this is the reason we have not put credit. but this library is safe to use because we monthly update dependencies and Gradle versions
